apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: kafka-client-hod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-client-hod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-client-hod
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: bitnami/kafka:3.1.0
        imagePullPolicy: IfNotPresent
        name: kafka-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
