apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-s3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-s3-app
  template:
    metadata:
      labels:
        app: kafka-s3-app
    spec:
      containers:
      - name: kafka-s3-app
        image: dihoda/kafka_s3_app:latest
